# -*- coding: utf-8 -*-
"""Spam_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4BefpdCHV9McFBXYKiLXmSkWiOSvdOR
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("spam.csv")
df.head()

df['label'] = df['label'].map({'ham': 0, 'spam': 1})

# Convert labels
df['label'] = df['label'].map({'spam': 1, 'ham': 0})

df.head()

X_train, X_test, y_train, y_test = train_test_split(
    df['text'], df['label'], test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer(stop_words='english')
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

test = ["Congratulations! You won a free laptop!!! Click here"]
test_vec = vectorizer.transform(test)
print(model.predict(test_vec))   # 1 = spam, 0 = ham